MIN_DELAY = 4
DEFUALT_RANKED = True
N_RANKED_FEATURES = 6
N_UNRANKED_FEATURES = N_RANKED_FEATURES - 2

CONGESTION, NUM_HALT, AVG_SPEED, CURR_STATE, LOCAL_RANK, GLOBAL_RANK = \
    range(N_RANKED_FEATURES)