MIN_DELAY = 4  # 5

## Depcrecated.
# Indices for the SUMO features for the observation spaces.
# N_FEATURES = 7
# NUM_VEHICLES, AVG_SPEED, NUM_OCCUPANCY, WAIT_TIME, TRAVEL_TIME, NUM_HALT, CURR_STATE = \
#     range(N_FEATURES)

N_RANKED_FEATURES = 6
N_UNRANKED_FEATURES = N_RANKED_FEATURES - 2

CONGESTION, NUM_HALT, AVG_SPEED, CURR_STATE, LOCAL_RANK, GLOBAL_RANK = \
    range(N_RANKED_FEATURES)