import numpy as np

from seal.sumo.config import NUM_TLS_STATES, N_RANKED_FEATURES, N_UNRANKED_FEATURES, SPACE_DTYPE
from gym.spaces import *
from typing import Any


def trafficlight_space(ranked: bool=False) -> Tuple:
    """This function generates the Tuple state space to support RL in seal. State spaces
       generated by this function are meant to be standardized in accordance with the
       configuration file (see `seal.sumo.kernel.const`). Generated state spaces are
       composed of several different features provided by TraCI (with some postprocessing)
       and rankings if specified via the `ranked` parameter.

    Args:
        ranked (bool, optional): Whether to include ranking features. Defaults to False.

    Returns:
        Tuple: Tuple OpenAI gym state space containing all the features.
    """
    n_features = N_RANKED_FEATURES if ranked else N_UNRANKED_FEATURES
    return Box(low=0.0, high=1.0, shape=(n_features,), dtype=SPACE_DTYPE)
